version: "3.7"
services:

    db:
        image: mariadb:10
        container_name: db
        restart: always
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: "database"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "rootpassword"

    wordpress-fpm:
        image: wordpress:5
        container_name: wordpress:fpm
        restart: always
        depends_on: ['db']
       # ports: ['8080:80']
        volumes:
            - www:/var/www/html
        environment:
            WORDPRESS_DB_HOST: "db"
            WORDPRESS_DB_NAME: "database"
            WORDPRESS_DB_USER: "user"
            WORDPRESS_DB_PASSWORD: "password"

    nginx: 
        image: nginx
        depends_on:
            - wordpress-fpm
        volumes:
            - ./conf.d:/etc/nginx/conf.d
            - www:/var/www/html
        ports:
            - 8080:80
volumes:
    db_data:
    WWW:
