version: "3.7"
services: 

  db:
    image: mariadb:10
    container_name: wp-60sec-db
    environment:
      MYSQL_DATABASE: "mariadb"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "rootpassword"
  
  wordpress-fpm:
    image: wordpress:5-fpm-alpine
    container_name: wp-60sec-fpm
    links:
      - db
    volumes:
      - wp_files:/var/www/html
    environment:
      WORDPRESS_DB_HOST: "db"
      WORDPRESS_DB_NAME: "mariadb"
      WORDPRESS_DB_USER: "user"
      WORDPRESS_DB_PASSWORD: "password"
  
  nginx:
    image: nginx:alpine
    container_name: wp-60sec-nginx
    depends_on: 
      - wordpress-fpm
    ports:
      - 8085:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - wp_files:/var/www/html

volumes: 
  wp_files: