version: "3.7"
services:

    db:
        image: mariadb:10
        container_name: db
        restart: always
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: "database"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "rootpassword"

    wordpress:
        image: wordpress:5
        container_name: wordpress
        restart: always
        links: ['db']
        depends_on: ['db']
        ports: ['8080:80']
        volumes:
            - www:/var/www/html
        environment:
            WORDPRESS_DB_HOST: "db"
            WORDPRESS_DB_NAME: "database"
            WORDPRESS_DB_USER: "user"
            WORDPRESS_DB_PASSWORD: "password"
volumes:
    db_data:
